language: go
go:
- 1.6
env:
  global:
  - SSH_KEY="id_rsa"
  - GIT_NAME="zf@bupt.edu.cn"
  - GIT_EMAIL="zf@bupt.edu.cn"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_b8a265b64f65_key -iv $encrypted_b8a265b64f65_iv
  -in id_rsa.enc -out id_rsa -d
install:
- go get -u -v github.com/spf13/hugo
script:
- git https://github.com/alexurquhart/hugo-geo.git ./themes/hugo-geo
- hugo
after_success:
- echo "zfwmr.github.io" > ./public/CNAME
- ./scripts/deploy.sh
