baseurl = "https://zfwmr.github.io/"
title = "wmr"
languageCode = "zh-cn"
theme = "hyde"
##theme = "hugo-alabaster-theme"
##theme = "next" error
##theme = "hugo-theme-next" error

[params]
	themeColor = "theme-base-0c"
##	logo      = "/images/logo.jpg"
    description = "痛苦让人成长"
    email = "zf@bupt.edu.cn"
    hostname = "pyto.ml"
[permalinks]
    post = "/:year/:title/"
    addendum = "/addendum/:year/:title/"
